### ISSUE TITLE
invalid characters in hostname

### ISSUE THREAD

**Issue by flare04** [gavincarr/nagios-http#1]
if ($hostname =~ m! ^([-\w]+)$ !x) {                                                                                                               │·········
    $hostname = $1;                                                                                                                                  │·········
  } else {                                                                                                                                           │·········
    die "Invalid characters in hostname '$hostname'";                                                                                                │·········
  }
This fails when given this command
/usr/lib/nagios/plugins/nagios_http_cronjob -n Mongo_Connect_Check -C \"'/usr/lib64/nagios/plugins/check_mongodb.py -H localhost -A connect -P 27017 -W 2 -C 4 -d database -u nagios -p password'\" --hostname db21.example.com --freq 30 -v

Invalid characters in hostname 'db21.example.com' at /usr/lib/nagios/plugins/nagios_http_cronjob line 75.
Changing the above code to:-
if ($hostname) {
  if ($hostname =~ m! ^( .*?\. [^/]+ )$ !x) {
    $hostname = $1;                                                                                                  
  } else { 
    die "Invalid characters in hostname '$hostname'";                                         
  }                                                                                                                  
}
Seems to resolve the issue I was having

**Comment by gavincarr** [comment]
Thanks flare, I guess we've been using non-fully-qualified domains so far (it's the dots, not the numbers). I've pushed a fix and released version 0.9.4.
